name: GitHub Actions Docker
on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      
    - name: Check
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push client
      with:
        context: ./client
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/multi-client:latest

    - name: Build and push nginx
      with:
        context: ./nginx
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/multi-nginx:latest

    - name: Build and push server
      with:
        context: ./server
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/multi-server:latest

    - name: Build and push worker
      with:
        context: ./worker
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/multi-worker:latest
