name: GitHub Actions Docker
on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: 
      - docker build -t p0wer/multi-client ./client
      - docker build -t p0wer/multi-nginx ./nginx
      - docker build -t p0wer/multi-server ./server
      - docker build -t p0wer/multi-worker ./worker